services:

    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $projectDir: '%kernel.project_dir%'
            $cacheDir: '%kernel.cache_dir%'

    A2Global\CRMBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    A2Global\CRMBundle\Controller\:
        resource: '../../../src/Controller'
        tags: ['controller.service_arguments']

    A2Global\CRMBundle\EventListener\KernelRequestEventListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request }

#    A2Global\CRMBundle\EventListener\DoctrineEventListener:
#        tags:
#            - { name: doctrine.event_listener, event: 'prePersist' }

    A2Global\CRMBundle\Registry\EntityFieldRegistry:
        arguments: [!tagged { tag: 'a2crm.entity_field_type' }]

    a2crm.modifier.database_schema:
        class: A2Global\CRMBundle\Modifier\SchemaModifier
        public: true

    A2Global\CRMBundle\Modifier\SchemaModifier: '@a2crm.modifier.database_schema'