services:

    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    a2crm.my.super.service:
        class: A2Global\CRMBundle\MySuperService
        public: true

    A2Global\CRMBundle\Controller\:
        resource: '../../../src/Controller'
        tags: ['controller.service_arguments']

    A2Global\CRMBundle\MySuperService: '@a2crm.my.super.service'