services:

    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $projectDir: '%kernel.project_dir%'

    A2Global\CRMBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    A2Global\CRMBundle\Controller\:
        resource: '../../../src/Controller'
        tags: ['controller.service_arguments']

    _instanceof:
        A2Global\CRMBundle\Component\Field\FieldInterface:
            tags: ['a2crm.entity_field']
        A2Global\CRMBundle\Datasheet\DatasheetBuilder\DatasheetBuilderInterface:
            tags: ['a2crm.datasheet.builder']

    A2Global\CRMBundle\Registry\EntityFieldRegistry:
        arguments: [!tagged { tag: 'a2crm.entity_field' }]

    A2Global\CRMBundle\Registry\DatasheetBuilderRegistry:
        arguments: [!tagged { tag: 'a2crm.datasheet.builder' }]