services:

    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    A2Global\CRMBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    A2Global\CRMBundle\Controller\:
        resource: '../../../src/Controller'
        tags: ['controller.service_arguments']

    a2crm.modifier.database_schema:
        class: A2Global\CRMBundle\Modifier\SchemaModifier
        public: true

    A2Global\CRMBundle\Modifier\SchemaModifier: '@a2crm.modifier.database_schema'